project_id = "mziuxsfxevjnmdwnrqjs"

[functions.clawdbot]
verify_jwt = false

[functions.clawd-bot]
verify_jwt = false

[functions.invoice-api]
verify_jwt = false

[functions.google-drive]
verify_jwt = false

[functions.gmail-api]
verify_jwt = false

[functions.instagram-api]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.v0-designer]
verify_jwt = false

[functions.image-generator]
verify_jwt = false

[functions.prompt-machine]
verify_jwt = false

[functions.v0-poll]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.book-meeting]
verify_jwt = false

[functions.email-scheduler]
verify_jwt = false

[functions.script-ai]
verify_jwt = false

[functions.share-content]
verify_jwt = false

[functions.ringcentral-webhook]
verify_jwt = false

[functions.ringcentral-subscribe]
verify_jwt = false

[functions.higgsfield-api]
verify_jwt = false

[functions.telegram-media-listener]
verify_jwt = false

[functions.nano-banana]
verify_jwt = false

[functions.smm-api]
verify_jwt = false

[functions.ig-dm-notify]
verify_jwt = false

[functions.smm-scheduler]
verify_jwt = false

[functions.invoice-scheduler]
verify_jwt = false
