project_id = "mziuxsfxevjnmdwnrqjs"

[functions.clawdbot]
verify_jwt = false

[functions.clawd-bot]
verify_jwt = false

[functions.invoice-api]
verify_jwt = false

[functions.google-drive]
verify_jwt = false

[functions.gmail-api]
verify_jwt = false

[functions.instagram-api]
verify_jwt = false

[functions.zapier-webhook]
verify_jwt = false

[functions.ringcentral-api]
verify_jwt = false
